var json_LIBERTAD_MANUELFELIPERUGELESMunicipio_Capacho_Viejo_Parroquia_Manuel_Felipe_RugelesManuel_Felipe_Rugeles_Oronimia_7 = {
"type": "FeatureCollection",
"name": "LIBERTAD_MANUELFELIPERUGELESMunicipio_Capacho_Viejo_Parroquia_Manuel_Felipe_RugelesManuel_Felipe_Rugeles_Oronimia_7",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "pk": "1", "id": "1", "código": "201503", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "15", "municipio": "Capacho Viejo", "capital_mu": "Capacho Viejo", "código_par": "3", "parroquia": "Manuel Felipe Rúgeles", "capital_pa": "El Pueblito", "nombre": "Páramo La Laja", "fuente": "Digitalizado a partir de las Cartas Topográficas 1:25000 y 1:100000. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.302028017783286, 7.793991467734158 ] ] } },
{ "type": "Feature", "properties": { "pk": "2", "id": "2", "código": "201503", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "15", "municipio": "Capacho Viejo", "capital_mu": "Capacho Viejo", "código_par": "3", "parroquia": "Manuel Felipe Rúgeles", "capital_pa": "El Pueblito", "nombre": "Cerro la Golondrina", "fuente": "Digitalizado a partir de las Cartas Topográficas 1:25000 y 1:100000. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.303845866510628, 7.743277695118513 ] ] } },
{ "type": "Feature", "properties": { "pk": "3", "id": "3", "código": "201503", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "15", "municipio": "Capacho Viejo", "capital_mu": "Capacho Viejo", "código_par": "3", "parroquia": "Manuel Felipe Rúgeles", "capital_pa": "El Pueblito", "nombre": "Cerro San Felipe", "fuente": "Digitalizado a partir de las Cartas Topográficas 1:25000 y 1:100000. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.304766174878907, 7.726691581519023 ] ] } },
{ "type": "Feature", "properties": { "pk": "4", "id": "4", "código": "201503", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "15", "municipio": "Capacho Viejo", "capital_mu": "Capacho Viejo", "código_par": "3", "parroquia": "Manuel Felipe Rúgeles", "capital_pa": "El Pueblito", "nombre": "Cerro Agua Linda", "fuente": "Digitalizado a partir de las Cartas Topográficas 1:25000 y 1:100000. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.290110973834885, 7.725197523938331 ] ] } },
{ "type": "Feature", "properties": { "pk": "5", "id": "5", "código": "201503", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "15", "municipio": "Capacho Viejo", "capital_mu": "Capacho Viejo", "código_par": "3", "parroquia": "Manuel Felipe Rúgeles", "capital_pa": "El Pueblito", "nombre": "Cerro Mariana", "fuente": "Digitalizado a partir de las Cartas Topográficas 1:25000 y 1:100000. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.28067421396895, 7.701101490834062 ] ] } }
]
}
